apiVersion: v1
kind: Service
metadata:
  name: {{ template "ibm-content-navigator.fullname" . }}
  labels:
    app: {{ template "ibm-content-navigator.name" . }}
    chart: {{ template "ibm-content-navigator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
  - port: {{ .Values.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if eq .Values.service.type "NodePort" }}
    {{- if .Values.service.httpNodePort }}
    nodePort: {{ .Values.service.httpNodePort }}
    {{- end }}
    {{- end }} 
  - port: {{ .Values.service.httpsPort }}
    targetPort: https
    protocol: TCP
    name: https
    {{- if eq .Values.service.type "NodePort" }}
    {{- if .Values.service.httpsNodePort }}
    nodePort: {{ .Values.service.httpsNodePort }}
    {{- end }}
    {{- end }} 
  selector:
    app: {{ template "ibm-content-navigator.name" . }}
    release: {{ .Release.Name }}
